// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StripProjectEF;

namespace StripProjectEF.Migrations
{
    [DbContext(typeof(StripsContext))]
    [Migration("20211201092849_commit3")]
    partial class commit3
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("StripProjectEF.Model.Auteur", b =>
                {
                    b.Property<int>("AuteurID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuteurID");

                    b.ToTable("Auteurs");
                });

            modelBuilder.Entity("StripProjectEF.Model.AuteurStrip", b =>
                {
                    b.Property<int>("StripID")
                        .HasColumnType("int");

                    b.Property<int>("AuteurID")
                        .HasColumnType("int");

                    b.HasKey("StripID", "AuteurID");

                    b.HasIndex("AuteurID");

                    b.ToTable("AuteurStrip");
                });

            modelBuilder.Entity("StripProjectEF.Model.Reeks", b =>
                {
                    b.Property<int>("ReeksID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReeksID");

                    b.ToTable("Reeksen");
                });

            modelBuilder.Entity("StripProjectEF.Model.Strip", b =>
                {
                    b.Property<int>("StripID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Nr")
                        .HasColumnType("int");

                    b.Property<int?>("ReeksID")
                        .HasColumnType("int");

                    b.Property<string>("Titel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UitgeverijID")
                        .HasColumnType("int");

                    b.HasKey("StripID");

                    b.HasIndex("ReeksID");

                    b.HasIndex("UitgeverijID");

                    b.ToTable("Strips");
                });

            modelBuilder.Entity("StripProjectEF.Model.Uitgeverij", b =>
                {
                    b.Property<int>("UitgeverijID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Naam")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UitgeverijID");

                    b.ToTable("Uitgeverijen");
                });

            modelBuilder.Entity("StripProjectEF.Model.AuteurStrip", b =>
                {
                    b.HasOne("StripProjectEF.Model.Auteur", "Auteur")
                        .WithMany("StripsLink")
                        .HasForeignKey("AuteurID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StripProjectEF.Model.Strip", "Strip")
                        .WithMany("AuteursLink")
                        .HasForeignKey("StripID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Auteur");

                    b.Navigation("Strip");
                });

            modelBuilder.Entity("StripProjectEF.Model.Strip", b =>
                {
                    b.HasOne("StripProjectEF.Model.Reeks", "Reeks")
                        .WithMany("Strips")
                        .HasForeignKey("ReeksID");

                    b.HasOne("StripProjectEF.Model.Uitgeverij", "Uitgever")
                        .WithMany()
                        .HasForeignKey("UitgeverijID");

                    b.Navigation("Reeks");

                    b.Navigation("Uitgever");
                });

            modelBuilder.Entity("StripProjectEF.Model.Auteur", b =>
                {
                    b.Navigation("StripsLink");
                });

            modelBuilder.Entity("StripProjectEF.Model.Reeks", b =>
                {
                    b.Navigation("Strips");
                });

            modelBuilder.Entity("StripProjectEF.Model.Strip", b =>
                {
                    b.Navigation("AuteursLink");
                });
#pragma warning restore 612, 618
        }
    }
}
